"""Add due_date, color, and priority to Task model

Revision ID: 2640b3a50a30
Revises: 
Create Date: 2024-05-25 12:11:08.114113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2640b3a50a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('priority')
        batch_op.drop_column('color')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
